name: dine-soh deploiement
run-name: ${{github.actor}}

on:
  workflow_dispatch:

jobs:
  install-lint-build-test:
    name: Install, Lint, Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Lint code
        run: npm run lint

      - name: Build the project
        run: npm run build

      - name: Run tests (placeholder)
        run: echo "C'est la partie test"
