name: Déploiement Preprod

on:
  workflow_dispatch:  # Déclenchement manuel

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
      SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Installation des dépendances
        run: npm install

      - name: Build de l'application
        run: npm run build

      - name: Déploiement sur Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: ''  # On enlève --prebuilt
          working-directory: ./
          scope: ${{ secrets.VERCEL_SCOPE }}
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
